server:
  port: 8080

spring:
  application:
    name: seata-saga-rm-one
eureka:
  client:
    service-url:
      defaultZone: http://192.168.202.137:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
