server:
  port: 8082

spring:
  datasource:
    saga:
      driver-class: com.alibaba.druid.proxy.DruidDriver
      url: jdbc:mysql://127.0.0.1:3306/seata_saga
      username: root
      password: 123456
  application:
    name: seata-sage-tm-feign

eureka:
  client:
    service-url:
      defaultZone: http://192.168.202.137:8761/eureka
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

# Ribbon
ribbon:
  ReadTimeout: 20000 # 请求处理的超时时间
  ConnectTimeout: 10000 # 请求连接的超时时间
  #MaxAutoRetries: 0
  #OkToRetryOnAllOperations: false #Whether all operations can be retried for this client
  OkToRetryOnAllOperations: false
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0